name: Gradle Kotlin DSL Cucumber Configuration CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Cucumber Tests
        run: ./gradlew cucumber
      - name: Jacoco
        run: ./gradlew jacocoTestReport
      - name: Codecov
        uses: codecov/codecov-action@v1
